language: objective-c

before_install: 
  - brew update
  - brew remove xctool
  - brew install xctool

script: xctool -reporter pretty -project OOP-Cards-Model.xcodeproj -sdk iphonesimulator7.0 -scheme OOP-Cards-Model build test
